#!/usr/bin/env python3
"""
Unicode 数据生成脚本示例
从 Unicode Character Database 生成 C++ 静态数据表

用法：
  python3 generate_unicode_data.py --version 15.1.0 --output UnicodeData.cpp
"""

import urllib.request
import sys
import argparse
from pathlib import Path

class UnicodeDataGenerator:
    def __init__(self, version="15.1.0"):
        self.version = version
        self.base_url = f"https://www.unicode.org/Public/{version}/ucd/"
        
        # 存储解析的数据
        self.id_start_ranges = []
        self.id_continue_ranges = []
        self.xid_start_ranges = []
        self.xid_continue_ranges = []
        
    def download_file(self, filename):
        """下载 Unicode 数据文件"""
        url = self.base_url + filename
        local_path = Path(filename)
        
        if not local_path.exists():
            print(f"Downloading {url}...")
            urllib.request.urlretrieve(url, filename)
        
        return local_path
    
    def parse_derived_core_properties(self):
        """解析 DerivedCoreProperties.txt"""
        filepath = self.download_file("DerivedCoreProperties.txt")
        
        # ID_Start 范围
        id_start = []
        # ID_Continue 范围
        id_continue = []
        # XID_Start 范围
        xid_start = []
        # XID_Continue 范围
        xid_continue = []
        
        with open(filepath, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                
                # 解析格式：码点范围 ; 属性
                parts = line.split(';')
                if len(parts) < 2:
                    continue
                
                codepoints = parts[0].strip()
                prop = parts[1].strip().split('#')[0].strip()
                
                # 解析码点范围
                if '..' in codepoints:
                    start_hex, end_hex = codepoints.split('..')
                    start = int(start_hex, 16)
                    end = int(end_hex, 16)
                else:
                    start = int(codepoints, 16)
                    end = start
                
                # 分类属性
                if prop == 'ID_Start':
                    id_start.append((start, end))
                elif prop == 'ID_Continue':
                    id_continue.append((start, end))
                elif prop == 'XID_Start':
                    xid_start.append((start, end))
                elif prop == 'XID_Continue':
                    xid_continue.append((start, end))
        
        self.id_start_ranges = self.merge_ranges(id_start)
        self.id_continue_ranges = self.merge_ranges(id_continue)
        self.xid_start_ranges = self.merge_ranges(xid_start)
        self.xid_continue_ranges = self.merge_ranges(xid_continue)
    
    def merge_ranges(self, ranges):
        """合并连续的范围"""
        if not ranges:
            return []
        
        # 按起始点排序
        sorted_ranges = sorted(ranges)
        merged = [sorted_ranges[0]]
        
        for start, end in sorted_ranges[1:]:
            last_start, last_end = merged[-1]
            
            # 如果当前范围与上一个范围连续或重叠，合并
            if start <= last_end + 1:
                merged[-1] = (last_start, max(last_end, end))
            else:
                merged.append((start, end))
        
        return merged
    
    def generate_cpp_code(self, output_file):
        """生成 C++ 代码"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"""//===--- UnicodeData.cpp - Unicode Character Data --------*- C++ -*-===//
//
// Auto-generated from Unicode {self.version}
// DO NOT EDIT - Generated by generate_unicode_data.py
//
//===----------------------------------------------------------------------===//

#include "blocktype/Unicode/UnicodeData.h"
#include <algorithm>

namespace blocktype {{
namespace unicode {{

//===----------------------------------------------------------------------===//
// ID_Start Ranges
//===----------------------------------------------------------------------===//

struct CodePointRange {{
  uint32_t Start;
  uint32_t End;
}};

static constexpr CodePointRange IDStartRanges[] = {{
""")
            
            # 写入 ID_Start 范围
            for start, end in self.id_start_ranges:
                f.write(f"  {{0x{start:04X}, 0x{end:04X}}},\n")
            
            f.write("""};

static constexpr size_t IDStartRangesSize = sizeof(IDStartRanges) / sizeof(CodePointRange);

bool isIDStart(uint32_t CodePoint) {
  // 快速路径：ASCII 字符
  if (CodePoint < 0x80) {
    return (CodePoint >= 'A' && CodePoint <= 'Z') ||
           (CodePoint >= 'a' && CodePoint <= 'z') ||
           CodePoint == '_';
  }
  
  // 二分查找
  const CodePointRange *Begin = IDStartRanges;
  const CodePointRange *End = IDStartRanges + IDStartRangesSize;
  
  auto It = std::lower_bound(Begin, End, CodePoint,
    [](const CodePointRange &R, uint32_t CP) {
      return R.End < CP;
    });
  
  return It != End && CodePoint >= It->Start;
}

//===----------------------------------------------------------------------===//
// ID_Continue Ranges
//===----------------------------------------------------------------------===//

static constexpr CodePointRange IDContinueRanges[] = {
""")
            
            # 写入 ID_Continue 范围
            for start, end in self.id_continue_ranges:
                f.write(f"  {{0x{start:04X}, 0x{end:04X}}},\n")
            
            f.write("""};

static constexpr size_t IDContinueRangesSize = sizeof(IDContinueRanges) / sizeof(CodePointRange);

bool isIDContinue(uint32_t CodePoint) {
  // 快速路径：ASCII 字符
  if (CodePoint < 0x80) {
    return (CodePoint >= 'A' && CodePoint <= 'Z') ||
           (CodePoint >= 'a' && CodePoint <= 'z') ||
           (CodePoint >= '0' && CodePoint <= '9') ||
           CodePoint == '_';
  }
  
  // 二分查找
  const CodePointRange *Begin = IDContinueRanges;
  const CodePointRange *End = IDContinueRanges + IDContinueRangesSize;
  
  auto It = std::lower_bound(Begin, End, CodePoint,
    [](const CodePointRange &R, uint32_t CP) {
      return R.End < CP;
    });
  
  return It != End && CodePoint >= It->Start;
}

//===----------------------------------------------------------------------===//
// XID_Start Ranges
//===----------------------------------------------------------------------===//

static constexpr CodePointRange XIDStartRanges[] = {
""")
            
            # 写入 XID_Start 范围
            for start, end in self.xid_start_ranges:
                f.write(f"  {{0x{start:04X}, 0x{end:04X}}},\n")
            
            f.write("""};

static constexpr size_t XIDStartRangesSize = sizeof(XIDStartRanges) / sizeof(CodePointRange);

bool isXIDStart(uint32_t CodePoint) {
  // 快速路径：ASCII 字符
  if (CodePoint < 0x80) {
    return (CodePoint >= 'A' && CodePoint <= 'Z') ||
           (CodePoint >= 'a' && CodePoint <= 'z') ||
           CodePoint == '_';
  }
  
  // 二分查找
  const CodePointRange *Begin = XIDStartRanges;
  const CodePointRange *End = XIDStartRanges + XIDStartRangesSize;
  
  auto It = std::lower_bound(Begin, End, CodePoint,
    [](const CodePointRange &R, uint32_t CP) {
      return R.End < CP;
    });
  
  return It != End && CodePoint >= It->Start;
}

//===----------------------------------------------------------------------===//
// XID_Continue Ranges
//===----------------------------------------------------------------------===//

static constexpr CodePointRange XIDContinueRanges[] = {
""")
            
            # 写入 XID_Continue 范围
            for start, end in self.xid_continue_ranges:
                f.write(f"  {{0x{start:04X}, 0x{end:04X}}},\n")
            
            f.write("""};

static constexpr size_t XIDContinueRangesSize = sizeof(XIDContinueRanges) / sizeof(CodePointRange);

bool isXIDContinue(uint32_t CodePoint) {
  // 快速路径：ASCII 字符
  if (CodePoint < 0x80) {
    return (CodePoint >= 'A' && CodePoint <= 'Z') ||
           (CodePoint >= 'a' && CodePoint <= 'z') ||
           (CodePoint >= '0' && CodePoint <= '9') ||
           CodePoint == '_';
  }
  
  // 二分查找
  const CodePointRange *Begin = XIDContinueRanges;
  const CodePointRange *End = XIDContinueRanges + XIDContinueRangesSize;
  
  auto It = std::lower_bound(Begin, End, CodePoint,
    [](const CodePointRange &R, uint32_t CP) {
      return R.End < CP;
    });
  
  return It != End && CodePoint >= It->Start;
}

} // namespace unicode
} // namespace blocktype
""")

def main():
    parser = argparse.ArgumentParser(description='Generate Unicode data tables for BlockType compiler')
    parser.add_argument('--version', default='15.1.0', help='Unicode version (default: 15.1.0)')
    parser.add_argument('--output', default='UnicodeData.cpp', help='Output file name')
    
    args = parser.parse_args()
    
    print(f"Generating Unicode {args.version} data tables...")
    
    generator = UnicodeDataGenerator(args.version)
    generator.parse_derived_core_properties()
    
    print(f"ID_Start ranges: {len(generator.id_start_ranges)}")
    print(f"ID_Continue ranges: {len(generator.id_continue_ranges)}")
    print(f"XID_Start ranges: {len(generator.xid_start_ranges)}")
    print(f"XID_Continue ranges: {len(generator.xid_continue_ranges)}")
    
    generator.generate_cpp_code(args.output)
    print(f"Generated {args.output}")

if __name__ == '__main__':
    main()
